In [88]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

Creating Tensors

In [2]:
#Scalar
scalar= torch.tensor(5)
scalar
 


tensor(5)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int

scalar.item()

5

In [10]:
torch.Tensor([[1,2,3],[4,5,6]])

torch.Tensor(np.array([[2,3,5],[1,4,6]]))

tensor([[2., 3., 5.],
        [1., 4., 6.]])

In [6]:
x=torch.Tensor([[1,2,3],[4,5,6]])
print(x[1][2])

tensor(6.)


In [22]:
#Vector

vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [23]:
vector.shape

torch.Size([2])

In [24]:
vector.ndim

1

In [25]:
#Matrix

MATRIX=torch.tensor([[1,2,3],
                     [4,5,6]])
MATRIX



tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
MATRIX.ndim

2

In [27]:
MATRIX.shape

torch.Size([2, 3])

In [28]:
MATRIX[1][2]

tensor(6)

In [29]:
#TENSOR

TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [41]:
TENSOR=torch.tensor([[[[1,2,3],
                       [4,5,6],
                       [7,8,9],
                       [10,11,12]]]])
TENSOR

tensor([[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9],
          [10, 11, 12]]]])

In [42]:
TENSOR.shape

torch.Size([1, 1, 4, 3])

In [43]:
TENSOR.ndim

4

In [44]:
TENSOR[0]

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [50]:
TENSOR[0][0][1][2]

tensor(6)

RANDOM TENSORS

In [54]:
#creating a random tensor

random_tensor=torch.rand(3,2,4)
random_tensor

tensor([[[0.0268, 0.6420, 0.6429, 0.8494],
         [0.2984, 0.5032, 0.9828, 0.8317]],

        [[0.9157, 0.6700, 0.7123, 0.8093],
         [0.2631, 0.3555, 0.9704, 0.4174]],

        [[0.0406, 0.1564, 0.1313, 0.9709],
         [0.4830, 0.2517, 0.4967, 0.3533]]])

In [55]:
random_tensor.shape

torch.Size([3, 2, 4])

In [56]:
random_tensor.ndim

3

Creating a random tensor with similar shape to an image tensor

In [57]:
random_image_tensor=torch.rand(size=(233,233,3)) ##hight,width,color channel
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([233, 233, 3]), 3)

ZEROS AND ONES TENSORS

In [58]:
zeros=torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [59]:
zeros.dtype

torch.float32

In [60]:
ones=torch.ones(size=(3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [61]:
zeros*ones

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

CREATING A RANGE OF TENSORS AND TENSORS-LIKE

In [64]:
range_tensor=torch.arange(1,11,2)
range_tensor

tensor([1, 3, 5, 7, 9])

In [65]:
like_tensor=torch.zeros_like(input=range_tensor)
like_tensor

tensor([0, 0, 0, 0, 0])

TENSORS DATATYPES

In [66]:
#Float_32 tensor

float_32_tensor=torch.tensor([3.,4.,5.],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 4., 5.])

In [67]:
float_32_tensor.dtype


torch.float32

In [68]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [70]:
float_16_tensor*float_32_tensor

tensor([ 9., 16., 25.])

In [71]:
int_32_tensor=torch.tensor([2,4,5],
                           dtype=None,
                           device=None,
                           requires_grad=False)
int_32_tensor

tensor([2, 4, 5])

In [72]:
float_32_tensor*int_32_tensor

tensor([ 6., 16., 25.])

Getting Information from Tensors

In [73]:
tensor_=torch.rand(3,4)
tensor_

tensor([[0.1437, 0.4380, 0.6706, 0.0017],
        [0.3463, 0.7511, 0.8636, 0.5406],
        [0.9607, 0.2546, 0.8514, 0.8701]])

In [74]:
print(tensor_)
print(f"DataType of tensor: {tensor_.dtype}")
print(f"Shape of tensor: {tensor_.shape}")
print(f"Device tensor is on: {tensor_.device}")

tensor([[0.1437, 0.4380, 0.6706, 0.0017],
        [0.3463, 0.7511, 0.8636, 0.5406],
        [0.9607, 0.2546, 0.8514, 0.8701]])
DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


Manipulating Tensors (Tensor Operations)

In [75]:
#Addition 

tensor=torch.tensor([1,2,3,4])
tensor+20

tensor([21, 22, 23, 24])

In [77]:
#Multiplication

tensor_mul=torch.tensor([1,2,3,4,5])
tensor_mul*3

tensor([ 3,  6,  9, 12, 15])

In [81]:
#division
tensor_div=torch.tensor([10,20,30,40])
tensor_div/2



tensor([ 5., 10., 15., 20.])

In [84]:
tens=torch.tensor([1,2,3])
tens_2=torch.tensor([4,5,6])
print(tens * tens_2)


tensor([ 4, 10, 18])


In [90]:
#Matrix Multiplication
torch.matmul(tens,tens_2)


tensor(32)

In [91]:
value=0
for i in range(len(tens)):
    value+= tens[i]*tens_2[i]
value

tensor(32)

In [92]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.0938, 0.7301],
        [0.1518, 1.2024]])

In [94]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.6210, 0.6695],
        [0.5047, 0.7269]])

In [98]:
torch.matmul(torch.rand(5,3),torch.rand(3,5))

tensor([[0.7463, 1.2962, 0.6276, 1.3740, 1.4342],
        [0.4146, 1.0586, 0.6865, 1.1093, 1.1413],
        [0.6377, 1.4341, 0.7351, 1.5887, 1.5651],
        [0.2624, 0.7980, 0.4468, 0.9063, 0.8591],
        [0.8230, 1.0045, 0.4433, 0.9695, 1.1393]])

In [99]:
#Shape for matrix multiplication

tensor_a=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_b=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
torch.matmul(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [100]:
tensor_a.shape , tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [103]:
#to fix the tensors shape issues we can use transpose
new_tensor_b=tensor_b.T

In [102]:
tensor_b

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [104]:
torch.matmul(tensor_a,new_tensor_b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Finding the min ,max, sum ,etc(tensor aggregation)

In [105]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [106]:
#Find Min
x.min()


tensor(0)

In [107]:
#find max
x.max()

tensor(90)

In [108]:
#find sum
x.sum()

tensor(450)

In [112]:
#mean
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

Finding the positional min and max

In [113]:
x.argmin()

tensor(0)

In [114]:
x[0]

tensor(0)

In [115]:
x.argmax()

tensor(9)

In [116]:
x[9]

tensor(90)

Reshaping


In [117]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [118]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [120]:
x_reshaped=x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

VIEW

In [121]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [122]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

Stacking

In [124]:
x_stacked=torch.stack((x,x,x,x),dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

SQUEEZE

In [129]:
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [130]:
z.shape

torch.Size([1, 9])

In [131]:
z.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [132]:
z.squeeze().shape

torch.Size([9])

UNSQUEEZE

In [133]:
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [134]:
z.shape

torch.Size([1, 9])

In [139]:
z.unsqueeze(dim=0)

tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [140]:
z.unsqueeze(dim=0).shape

torch.Size([1, 1, 9])

PERMUTE

In [144]:
x_original=torch.rand(size=(144,244,3))
x_original.shape


torch.Size([144, 244, 3])

In [145]:
x_permuted=x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 144, 244])

SELECTING DATA FROM TENSORS (INDEXING)

In [146]:
y=torch.arange(1,10).reshape(1,3,3)
y,y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [147]:
y[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [148]:
y[0][0]

tensor([1, 2, 3])

In [149]:
y[0][0][0]

tensor(1)

In [150]:
y[0][2]

tensor([7, 8, 9])

In [151]:
y[0][2][2]

tensor(9)

In [152]:
y[:,:,2]

tensor([[3, 6, 9]])

PyTorch Tensors and NumPy

In [154]:
#NumPy array to Tensor

array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [155]:
#change the values of array what will this do to tensor
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [158]:
#Tensor to NumPy array
tensor_1=torch.ones(7)
numpy_tensor=tensor_1.numpy()
tensor_1,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [160]:
#change the values of tensor what will this do to numpy array
tensor_1=tensor_1+1
tensor_1,numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

**Reproducibility**

In [161]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.8223, 0.9271, 0.2246, 0.6916],
        [0.1194, 0.0613, 0.1281, 0.3929],
        [0.3525, 0.3888, 0.7495, 0.5529]])
tensor([[0.7519, 0.6320, 0.8673, 0.2086],
        [0.0041, 0.1992, 0.5167, 0.9012],
        [0.1383, 0.3649, 0.0920, 0.6311]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [163]:
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
